### ISSUE TITLE
Re-add proper support to set ventilation level to "auto"

### ISSUE THREAD

**Issue by mweimerskirch** [adorobis/hacomfoairmqtt#10]
See #9

**Comment by adorobis** [comment]
What would the "auto" mode do? With the ComfoSense module attached auto is enabling the scheduled times but I'm not sure if the schedule is stored in the unit or in the ComfoSense module. If it is stored in the vent unit then also entire scheduling would need to be implemented, with the HA integration and the possibilities of automating it on HA level I think it is not worth the effort. Else if it is stored in the ComfoSense module then auto mode would not make sense anyway.

**Comment by mweimerskirch** [comment]
I don't know where the schedule would be stored. But you're right, it doesn't really make sense to add the "auto" option in the context of HomeAssistant.
