### ISSUE TITLE
Feature request: Add support for RS485 communication to WHR950

### ISSUE THREAD

**Issue by mogwai2** [adorobis/hacomfoairmqtt#17]
Would you consider adding support for the WHR950 based on the RS485 communication protocol:
https://matsab.de/de/heimautomatisierung/comfoair

Attached a modified version of your script that I made and tested.

What is working:
- Reading temperatures (only 3 sensors are supported, supply temperature to the house is not measured)
- Fan % and RPM

Not yet working:
- Reading comfort temperature (should be possible)
- Controlling fan level (cannot get it to work, not sure why)
- Some status stuff I still need to figure out

My modified version of the script. I see that quite some changes have been made in the meantime, I could merge my changes in the new version and test if that would help you...
[whr950.zip](https://github.com/adorobis/hacomfoairmqtt/files/5906851/whr950.zip)

**Comment by adorobis** [comment]
> My modified version of the script. I see that quite some changes have been made in the meantime, I could merge my changes in the new version and test if that would help you...
Yes, this would be the best approach - create your fork and implement the changes there, keep it in sync with the main branch as it is still quite in development.
A few more points to be considered:
1. It would require a configuration parameter (now in config.ini file) to define which version it is using: RS232 or RS485
2. With limited number of functions, especially the missing ones for controling the unit, it would require some additional parameters to define which functions are enabled.
3. You would need to figure out the checksum calculation method and return codes so it is in line with the way the program works now.

**Comment by mogwai2** [comment]
I managed to add basic RS485 support without major changes to the main code. I have no experience with github, but think I managed to create a pull request with my code updates. Please check it out.

**Comment by adorobis** [comment]
Basic support added in PR https://github.com/adorobis/hacomfoairmqtt/pull/18
Many thanks @mogwai2 !

**Comment by Theagainmen** [comment]
@mogwai2 thanks for the reply! Unfortunately the website seems to no longer exist... do you maybe have a copy of the information that was on the website? Or anything that could help me? I want to try control commands too.

**Comment by mogwai2** [comment]
Yes I did use the J.E. Stork Maintenance SW tool. You can change settings but e.g. not command to change fan speed from 1 to 2 or 3 (which is what I wanted).

**Comment by Theagainmen** [comment]
@mogwai2 thanks! I also recently tried the J.E. Stork Maintenance tool, but I keep getting the error 'No MX found..'. My current setup is:

Laptop USB --> RS485 converter --> Wires from this converter A <-> A, B <-> B, GND <-> GND.

The wiring itself should be correct, because when I send the read temperature command over this exact setup via a Serial program, it works fine! Do you have any idea what I need to change in order for it to work with the software tool? Maybe I can find some more info via the tool too.
