### ISSUE TITLE
Summer/Winter status

### ISSUE THREAD

**Issue by dsfsfse43423** [adorobis/hacomfoairmqtt#2]
According to the documentation http://www.see-solutions.de/sonstiges/Protokollbeschreibung_ComfoAir.pdf, you may want to update the bypass_status by swapping summer with winter status.

######## PROTOCOL ########
Kommando: 0x00 0xDF Status Bypassregelung abrufen
Daten: -
Antwort: 0x00 0xE0
Daten: 
Byte[1] 0x00
Byte[2] 0x00
Byte[3] Bypass Faktor
Byte[4] Bypass Stufe
Byte[5] Bypass korrektur
Byte[6] 0x00
Byte[7] Sommermodus (1 = ja / 0 = nein (Winter))
######## CA350 ########
def get_bypass_status():
    # 0x07 0xF0 0x00 0x0B 0x00 0xB8 0x07 0x0F 
    # Checksum: 0xB8 (0x00 0x0B) = 0 + 11 + 0 + 173 = 184
    # End: 0x07 0x0F

    data = serial_command(b'\x07\xF0\x00\xDF\x00\x8C\x07\x0F')

    if data == None:
        warning_msg('function get_bypass_status could not get serial data')
    else:
        if len(data) > 8:
            BypassStatus = int(data[10], 16)
            SummerMode = int(data[13],16)
            publish_message(msg=str(BypassStatus), mqtt_path='comfoair/bypassstatus')
            if SummerMode==1:
                publish_message(msg='Summer', mqtt_path='comfoair/bypassmode')
            else:
                publish_message(msg='Winter', mqtt_path='comfoair/bypassmode')
        else:
            warning_msg('function get_bypass_status data array too short')

**Comment by adorobis** [comment]
@dsfsfse43423 Yes, right, many thanks! I was wondering why my vent is working in winter mode :)

**Comment by adorobis** [comment]
Code corrected.
