### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by SgtFoose** [adorobis/hacomfoairmqtt#39]
Hi, I came across your repo and I'm trying to install it to Home Assistant on a Pi4b.
I have the MQTT broker already running in HA but I'm struggling with the instructions from the readme.me
file (please forgive my noob knowledge). I also happen to have a seperate Pi3b with Pi OS which can be used
to connect to my Storkair WHR930 (same as comfoair).

When I run "source /usr/local/share/ca350/bin/activate.csh", I get this:

pi@raspberrypi:/usr/local/share/ca350/bin $ source /usr/local/share/ca350/bin/activate.csh
_**-bash: alias: deactivate: niet gevonden
-bash: alias: 'test $?_OLD_VIRTUAL_PATH !': ongeldige naam voor alias
-bash: deactivate: opdracht niet gevonden
-bash: setenv: opdracht niet gevonden
-bash: setenv: opdracht niet gevonden
-bash: /usr/local/share/ca350/bin/activate.csh: regel 26: syntaxfout: onverwacht bestandseinde**_

Sorry for Dutch, but it basically says:

**_-bash: alias: deactivate: not found
-bash: alias: 'test $?_OLD_VIRTUAL_PATH !': invalid name for alias
-bash: deactivate: command not found
-bash: setenv: command not found
-bash: setenv: command not found
-bash: /usr/local/share/ca350/bin/activate.csh: regel 26: syntaxerror: unexpected fileend_**

Is this because I'm not running FreeBSD (e.g. TrueNAS)?

**Comment by adorobis** [comment]
As this instructions (and my environment) is on TrueNAS (FreeBSD based) the commands might be slightly different on Linux distributions. Try to replace the command with:
`source /usr/local/share/ca350/bin/activate`
Also the file locations are what is typical on FreeBSD, might not be the best (or at least not standard) on Linux

**Comment by adorobis** [comment]
And btw, the creation and config of the daemon (service) is completely different on Linux. You would need to find a guide how to do it.

**Comment by SgtFoose** [comment]
![HomeAssistantMqttStorkairWHR930 Test1](https://user-images.githubusercontent.com/17387175/212148247-d3178dfc-cce7-4e14-a42e-f976aca532b0.png)
If I just run the ca350.py script I do get all the stuff running on a Rpi3b with PiOS Lite... I will spend little more time!

**Comment by adorobis** [comment]
Stale
