### ISSUE TITLE
measure internal API break

### ISSUE THREAD

**Issue by zanac** [adorobis/hacomfoairmqtt#42]
![image](https://github.com/adorobis/hacomfoairmqtt/assets/21194919/e6ce7d31-8dd9-45ae-9080-27065b884edc)

I just publish a small "pull request" that fix a little issue: i'm developing a nice card that using internal Home Assistant API make a graph of external home temperature that i get from CA350 sensor... without this patch i cannot use ca350_outside_temperature

**Comment by adorobis** [comment]
Solved for all relevant sensors with the latest commit:
https://github.com/adorobis/hacomfoairmqtt/commit/e042691aad23d647d1de31e2472d3959fa4598c6
