### ISSUE TITLE
ca350 sensor name deprecated

### ISSUE THREAD

**Issue by zanac** [adorobis/hacomfoairmqtt#45]
From HA 2024.2.0 ca350 sensors will stop to work... here you are the warning that i get upgrading to latest home assistant (sorry it's in italian)...

Alcune entità MQTT hanno un nome di entità che inizia con il nome del dispositivo. Questo non è previsto. Per evitare un nome duplicato, il prefisso del nome del dispositivo viene privato del nome dell'entità come soluzione alternativa. Si prega di informare il manutentore dell'applicazione software che fornisce le entità interessate per risolvere questo problema.

Elenco delle entità interessate:

binary_sensor.ca350_preheating_status
binary_sensor.ca350_summer_mode
sensor.ca350_supply_temperature
number.ca350_filter_weeks
sensor.ca350_summer_mode
sensor.ca350_analog_sensor_4
binary_sensor.ca350_filter_status
climate.ca350_climate
sensor.ca350_filter_hours
sensor.ca350_ewt_temperature
sensor.ca350_exhaust_temperature
sensor.ca350_analog_sensor_2
number.ca350_ewt_high_temperature
sensor.ca350_return_air_level
sensor.ca350_bypass_valve
sensor.ca350_analog_sensor_1
sensor.ca350_return_temperature
sensor.ca350_exhaust_fan_speed
sensor.ca350_analog_sensor_3
sensor.ca350_supply_fan_speed
button.ca350_reset_filter
number.ca350_ewt_low_temperature
binary_sensor.ca350_bypass_valve
sensor.ca350_supply_air_level
sensor.ca350_outside_temperature
number.ca350_ewt_speed_up

**Comment by zanac** [comment]
Sorry, just updated and see that you fixed it!

**Comment by adorobis** [comment]
Not me, credit goes to @PimDoos
