### ISSUE TITLE
Enable/disable ETW

### ISSUE THREAD

**Issue by TheFrisianDude** [adorobis/hacomfoairmqtt#47]
I am new here. I’ve been busy setting up my home assistant for a few days now. This thread was very helpful, thank you all!

We have a WHR930 (1 print version with only rj45 connector).
This is connected as indicated in this topic via a serial - usb adapter on a raspberry pi.

As a software I try the [adorobis](https://community.home-assistant.io/u/adorobis)/hacomfoairmqtt, first no connection to serial but after flipping tx/rx the script continues but stops with the error:

26-08-2023 06:14:42 DEBUG: Sending autodiscover for homeassistant/binary_sensor/ca350_bypass_valve/config
Traceback (most recent call last):
  File "/home/pi/ca350/ca350.py", line 1110, in <module>
    get_temp()
  File "/home/pi/ca350/ca350.py", line 374, in get_temp
    EWTTemp = data[6] / 2.0 - 20
IndexError: index out of range

I suspect this is because our WHR930 does not have the ETW.
In the config I don’t see an option to turn it off, does anyone know how to solve this?

**Comment by adorobis** [comment]
For now I've just included some fail safe check so it won't dump anymore. It seems that your device does not support EWT at all, I don't have it installed in my unit and it just returns some data (e.g. temp is 0) so now I'm checking if that data is returned.

**Comment by TheFrisianDude** [comment]
@adorobis thank you so much for your help.

I'm still getting an error:

28-08-2023 05:08:23 DEBUG: Sending autodiscover for homeassistant/sensor/ca350_ewttemp/config
    get_temp()
  File "/home/pi/ca350/ca350.py", line 383, in get_temp
    if EWTTemp is not None:
UnboundLocalError: local variable 'EWTTemp' referenced before assignment

**Comment by adorobis** [comment]
Oh, I'm sorry. I need to test it before committing. Will fix it ASAP

**Comment by adorobis** [comment]
It is fixed now, a bit difficult to fully test as my device behaves differently. Hope all works now for you. I wonder if there are also other features that are not available in your device.

**Comment by TheFrisianDude** [comment]
Thanks for your time and help, looks stable as far as i could test for now. EWT and analog sensors are the only values that are not available.

**Comment by TheFrisianDude** [comment]
> It is fixed now, a bit difficult to fully test as my device behaves differently. Hope all works now for you. I wonder if there are also other features that are not available in your device.

I noticed that the fan modes are not displaying correctly. 
To control the fan we use the perilex switch with 3 modes ( 3 1 2 ) were 1 is default/low, theres no off.

In the lovelace-hacomfoairmqtt card and in the automate generated HA climate card it displays fan as off when its actually on 1. 
When i turn the perilex switch to 2 the cards change to fan mode 1. 

Any ideas on how to fix this?

**Comment by adorobis** [comment]
Well, that is because in the Luxe versions (or in other words in those with programmable controllers) it has 3 speeds / levels + the "Away" mode. They are represented in the RS232 interface as 1, 2, 3 and 4 levels. The HA `climate` entity standard does not have an Away mode therefore it is represented as "Off" and then the 1, 2, 3 ones in the "On" state. It would require some adaptation of the code to configure which version of the unit it is connected to, so that it would not use the "Off"/Away mode. On the other hand this will be tricky as HA will always allow to turn off the `climate` entity and we would need to decide how the integration should behave in such case. Comfoair units don't have an option to be turned off...

**Comment by TheFrisianDude** [comment]
It's been a while, but I'm working on it again. I try to control the fan speed but it also doesn't work. When running the script it does indicate that the fan speed has changed when I send an mqtt message. No physical or mqtt changes after that.

`24-10-2023 05:03:27 DEBUG: published message OFF on topic comfoair/ca350_summer_mode at Tue Oct 24 07:03:27 2023
24-10-2023 05:03:29 DEBUG: published message OFF on topic comfoair/preheatingstatus at Tue Oct 24 07:03:29 2023
24-10-2023 05:03:31 WARNING: get_analog_sensor function could not get serial data
24-10-2023 05:03:33 WARNING: get_ewt function could not get serial data
comfoair/ha_climate_mode/fan/set is low (speed 20)
FanLevel 2
24-10-2023 05:03:37 INFO: Changed the ventilation to 2
24-10-2023 05:03:39 DEBUG: ReturnAirLevel: 25, SupplyAirLevel: 35, FanLevel: 1, IntakeFanActive: Yes
24-10-2023 05:03:39 DEBUG: published message off on topic comfoair/ha_climate_mode at Tue Oct 24 07:03:39 2023
24-10-2023 05:03:39 DEBUG: published message off on topic comfoair/ha_climate_mode/fan at Tue Oct 24 07:03:39 2023
24-10-2023 05:03:41 DEBUG: published message 35 on topic comfoair/intakefanspeed at Tue Oct 24 07:03:41 2023`


Any ideas on how to troubleshoot this?

**Comment by adorobis** [comment]
Do you still have the perilex switch connected? If yes, does HA show correct speed when you change the switch setting?

**Comment by adorobis** [comment]
OK, great. I don't know for sure but I think that you can't change the speed while the perilex switch is connected. It is hardwired and it will most likely have priority over the settings via RS232. So I'd disconnect the switch and check if controls from HA/MQTT work ok.

> it says off when on 1, low when on 2 medium when on 3.

As explained earlier: the comfoair units don't really have off state, even with other switches e.g. the programmable ones. It allows to set levels 1, 2, 3, and 4. Level 1 is considered an "away" mode, but it still keeps the vent running on a low (configurable) speed. On the other hand this does not match the standard in HA - you can have there off, Low, Medium and High. Hence the mapping 1 -> off, 2 -> low, 3 -> medium, and 4 -> high. There is no other way to do it and keep HA standard.
The only thing I could imagine is to enhance the program and allow configuration of the mapping for cases when the unit supports 3 speeds only. Btw, I believe that your unit also will support 4 levels, it is just that your perilex switch has 3 positions that is limiting it.

**Comment by TheFrisianDude** [comment]
Thanks! i will check it with perilex disconnected and will report back
