### ISSUE TITLE
Feedback: running rootless container with podman & usb-serial

### ISSUE THREAD

**Issue by maehtricks** [adorobis/hacomfoairmqtt#52]
Just some feedback on running the container rootless with podman and usb-serial adapter attached.

Installation was easy and it runs smooth, good job :sunglasses:

Last time I tried to mount the serial adapter for another project failed with compose because of rootless. For now I'm just going with podman run.

My variables are in a file called config.env and this is my run command: `podman run -d --name comfoair350 --restart=unless-stopped --env-file config.env --device /dev/ttyUSB0 --group-add keep-groups -e TZ=Europe/Berlin --network=host k42sde/hassioaddon-comfoair350:latest`

It would be an improvement for your docker-compose.yml to externalize the variables as well and to include them via "env_file".

**Comment by adorobis** [comment]
Thanks for sharing, I guess I can close this issue :)
